---
new_page_extension: html
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: index.html
  label: index
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
