---
new_page_extension: html
auto_deploy: false
admin_path: ''
webhook_url: 
sections: 
- type: document
  label: index
  path: index.html
  read_only: false
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
